server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://hospitaldb:5433/hospital
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: hospital
  rabbitmq:
    port: 5672
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

springdoc:
  api-docs:
    path: api/hospital/v3/api-docs
  swagger-ui:
    path: api/hospital/swagger-ui.html

jwt:
  secret: "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4"