server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: authentication
  rabbitmq:
    host: 127.0.0.1
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /api/authentication/v3/api-docs
  swagger-ui:
    path: /api/authentication/swagger-ui.html

jwt:
  secret: "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4"