server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/timetable
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: timetable
  rabbitmq:
    host: 127.0.0.1
    port: 5672

springdoc:
  api-docs:
    path: /api/timetable/v3/api-docs
  swagger-ui:
    path: /api/timetable/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4"
